### ISSUE TITLE
License model?

### ISSUE THREAD

**Issue by PEM--** [EvanHahn/mailtolink.js#2]
Thanks for sharing this library. Could you add a license model?

**Comment by EvanHahn** [comment]
I have a [LICENSE.txt](https://github.com/EvanHahn/mailtolink.js/blob/master/LICENSE.txt) and a [license key in the package.json](https://github.com/EvanHahn/mailtolink.js/blob/master/package.json#L19)—what do you mean by "license model"?

**Comment by PEM--** [comment]
My bad, I didn't see it. Thanks.

**Comment by EvanHahn** [comment]
No problem!
